controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Post;
use app\models\Post_translation;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['admin']);
            //return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['admin']);
            //return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /*
     * Admin action for list posts in admin page
     */
    public function actionAdmin()
    {
        //Check if we are logged
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['login']);
        }
        //Get languages from DB, for view choosing
        $languagesArr = Yii::$app->languagecomponent->getLanguages();

        //Language for get proper post from DB
        $request = Yii::$app->request;
        $session = Yii::$app->session;
        $language = Yii::$app->languagecomponent->getLanguage($request, $session);

        //Cache
        $cache = Yii::$app->cache;

        //Querry table Post_translations
        $queryPosts = Post_translation::find();

        //Pagination
        $totalCount = $cache->getOrSet('countPosts', function () use ($queryPosts) {
            return $queryPosts->count();
        });
        $pagination = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $totalCount,
        ]);

        //Cache dependency
        $postDependency = $cache->getOrSet('clientDependency', function () {
            return time();
        });

        //Get posts from DB, cache
        $posts = $cache->getOrSet('postsAdmin_'.$language.'_'.$pagination->offset.'_'.$pagination->limit.'_'.$postDependency,
            function () use ($queryPosts, $language, $pagination) {
                return $queryPosts
                    ->where(['post_translation.language_id' => $language])
                    ->andWhere(['post_translation.status' => '1'])
                    ->offset($pagination->offset)
                    ->limit($pagination->limit)
                    ->all();
            });

        //language for table view
        $tableLang = isset($posts[0]['language_id']) ? $posts[0]['language_id'] : '1';
        
        return $this->render('admin', [
            'posts' => $posts,
            'languagesArr' => $languagesArr,
            'pagination' => $pagination,
            'tableLang' => $tableLang,
        ]);
    }
    /*
     * Admin action to create post
     */
    public function actionCreate()
    {
        //Check if we are logged
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['login']);
        }
        //Get languages from DB, for view
        $languagesArr = Yii::$app->languagecomponent->getLanguages();

        //Load models
        $modelPost = new Post();
        $modelTransl = new Post_translation();

        $post = Yii::$app->request->post();
        //When form is submitted
        if(isset($post['Post']) && isset($post['Post_translation'])){
            //Save data to Post table
            $modelPost->date_created = $post['Post']['date_created'];
            //Save in Post table and prepare data for Post_translation
            if($modelPost->save()){
                //last saved id in post table
                $lastId = $modelPost->id;
                //save data to Post_translation table
                $modelTransl->post_id = $lastId;
                $modelTransl->language_id = $post['Post_translation']['language_id'];
                $modelTransl->title = $post['Post_translation']['title'];
                $modelTransl->short_description = $post['Post_translation']['short_description'];
                $modelTransl->description = $post['Post_translation']['description'];
                $modelTransl->source = $post['Post_translation']['source'];
                $modelTransl->date_created = $post['Post']['date_created'];

                //Save in Post_translation table, after successful save in Post table
                if($modelTransl->save()){
                    return $this->redirect(['admin']);
                }else{
                    return $this->redirect(['error', 'message' => 'Error while save data in DB' ]);
                }
            }else{
                return $this->redirect(['error', 'message' => 'Error while save data in DB' ]);
            }
        }
        //reset cache dependency
        $cache = Yii::$app->cache;
        $cache->set('clientDependency', time());

        return $this->render('create', [
            'modelPost'=> $modelPost,
            'modelTransl'=> $modelTransl,
            'languagesArr' => $languagesArr
        ]);
    }
    /*
     * Admin action to edit post
     */
    public function actionEdit(){
        //Check if we are logged
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['login']);
        }
        //Get post_id, language
        $request = Yii::$app->request;
        $get = $request->get();
        $id = $get['id'];
        $languageId = $get['language_id'];

        //Get languages from DB, for view
        $languagesArr = Yii::$app->languagecomponent->getLanguages();
        //When form is submitted
        if( !empty(Yii::$app->request->post()) ){
            //Get post data
            $postEdit = Yii::$app->request->post();

            if(!isset($postEdit['edit_checkbox'])) {
                //update Post_translation table
                $postTransEdit = Post_translation::findOne($postEdit['Post_translation']['id']);
                $postTransEdit->post_id = $postEdit['Post_translation']['post_id'];
                $postTransEdit->language_id = $postEdit['Post_translation']['language_id'];
                $postTransEdit->title = $postEdit['Post_translation']['title'];
                $postTransEdit->short_description = $postEdit['Post_translation']['short_description'];
                $postTransEdit->description = $postEdit['Post_translation']['description'];
                $postTransEdit->source = $postEdit['Post_translation']['source'];
                //update
                if ($postTransEdit->save()) {
                    return $this->redirect(['admin']);
                }else{
                    return $this->redirect(['error', 'message' => 'Error while edit data in DB' ]);
                }
            }elseif($postEdit['edit_checkbox'] == 1){
                //new translation post
                $postTranslation = new Post_translation();
                $postTranslation->post_id = $postEdit['Post_translation']['post_id'];
                $postTranslation->language_id = $postEdit['Post_translation']['language_id'];
                $postTranslation->title = $postEdit['Post_translation']['title'];
                $postTranslation->short_description = $postEdit['Post_translation']['short_description'];
                $postTranslation->description = $postEdit['Post_translation']['description'];
                $postTranslation->source = $postEdit['Post_translation']['source'];
                $postTranslation->date_created = date(' j-m-y');
                //save new translalation
                if ($postTranslation->save()) {
                    return $this->redirect(['admin']);
                }else{
                    return $this->redirect(['error', 'message' => 'Error while save data in DB' ]);
                }
            }
        }
        //Load model
        $modelTransl = new Post_translation();

views/site/about.php
<?php

/** @var yii\web\View $this */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/admin.php
<?php
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\bootstrap4;
use yii\bootstrap;

?>
<!-- Language -->
<div>
    <p>
        <?php foreach ($languagesArr as $languageId => $languageName): ?>
            <?= Html::a($languageName, ['/site/admin', 'language_id' => $languageId ], ['class'=>'btn btn-light']) ?>
        <?php endforeach; ?>
    </p>
</div>
<!-- End language -->
<!-- Add new article -->
<div>
    <p><?= Html::a('+', ['/site/create' ], ['class'=>'btn btn-info']) ?></p>
</div>
<!-- End add new article -->
<!-- Posts list -->
<?php if ($tableLang == '1'): ?>
    <?= $this->render('partials/tableAdminBg', ['posts' => $posts]) ?>
<?php elseif ($tableLang == '2'): ?>
    <?= $this->render('partials/tableAdminEn', ['posts' => $posts]) ?>
<?php elseif ($tableLang == '3'): ?>
    <?= $this->render('partials/tableAdminDe', ['posts' => $posts]) ?>
<?php endif; ?>
<!-- End post list -->
<!-- Pagination -->
<?= LinkPager::widget(['pagination' => $pagination]) ?>




views/site/contact.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap4\ActiveForm $form */
/** @var app\models\ContactForm $model */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/create.php
<?php

use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\bootstrap4\ActiveForm;
use codezeen\yii2\tinymce\TinyMce;
use yii\jui\DatePicker;
?>

<p><?= Html::a('<<<', ['/site/admin' ], ['class'=>'btn btn-info']) ?></p>
<div class="row">
    <div class="col-lg-5">
        <?php $form = ActiveForm::begin(['id' => 'create-form']); ?>
            <!--Date-->
            <?= $form->field($modelPost, 'date_created')->widget(DatePicker::className(), [
                'options' => ['class' => 'form-control'],
                'dateFormat' => 'dd-MM-yyyy'
            ])?>
            <!-- Language -->
            <?= $form->field($modelTransl, 'language_id')->dropdownList($languagesArr)->label('Language'); ?>
            <!-- Title -->
            <?= $form->field($modelTransl, 'title')->textInput()->label('Title') ?>
            <!-- Short Description -->
            <?= $form->field($modelTransl, 'short_description')->textarea(); ?>
            <!-- Description -->
            <?= $form->field($modelTransl, 'description')->widget(
                TinyMce::className(),
                [
                    'settings'        => [
                        'language'               => 'en',
                        'plugins'                => [
                            "advlist autolink lists link image charmap print preview hr anchor pagebreak",
                            "searchreplace visualblocks visualchars code fullscreen",
                            "insertdatetime media nonbreaking save table contextmenu directionality",
                            "template paste textcolor"
                        ],
                        'toolbar'                => "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | print preview media | forecolor backcolor",
                        'toolbar_items_size'     => 'small',
                        'image_advtab'           => true,
                        'relative_urls'          => false,
                    ],
                ]
            ) ?>
            <!-- Source -->
            <?= $form->field($modelTransl, 'source')->textInput() ?>
            <!-- Submit button -->
            <div class="form-group">
                <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'create-button']) ?>
            </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>


views/site/detail.php
<?php
use yii\helpers\Html;
?>
<!-- Language -->
<div>
    <p>
        <?php foreach ($languagesArr as $languageId => $languageName): ?>
            <?= Html::a($languageName, ['/site/detail', 'id' => $post->post_id, 'language_id' => $languageId ], ['class'=>'btn btn-light']) ?>
        <?php endforeach; ?>
    </p>
</div>
<!--End language-->
<!-- Post details -->
<p><?= Html::a('<<<', ['/site/admin' ], ['class'=>'btn btn-info']) ?></p>
<table class="table">
    <tr>
        <td><?= $post->title ?></td>
    </tr>
    <tr>
        <td><?= $post->date_created ?></td>
    </tr>
    <tr>
        <td><?= $post->description ?></td>
    </tr>
    <tr>
        <td><?= $post->source ?></td>
    </tr>
</table>
<!-- End post details -->

views/site/edit.php
<?php

use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\bootstrap4\ActiveForm;
use yii\jui\DatePicker;
use codezeen\yii2\tinymce\TinyMce;

?>
<p><?= Html::a('<<<', ['/site/admin' ], ['class'=>'btn btn-info']) ?></p>
<div class="row">
    <div class="col-lg-5">
        <?php $form = ActiveForm::begin(['id' => 'edit-form']); ?>
            <!-- Id -->
            <?= $form->field($modelTransl, 'id')->hiddenInput( [ 'value' => $post['id'] ])->label(false) ?>
            <!-- Post id -->
            <?= $form->field($modelTransl, 'post_id')->hiddenInput( [ 'value' => $post['post_id'] ])->label(false) ?>
            <!-- Language -->
            <?= $form->field($modelTransl, 'language_id')->dropdownList($languagesArr,
                                 ['options' => [ $post['language_id'] => ['selected' => true] ]])->label('Language'); ?>
            <!-- Title -->
            <?= $form->field($modelTransl, 'title')->textInput([ 'value' => $post['title'] ])->label('Title') ?>
            <!-- Short Description -->
            <?= $form->field($modelTransl, 'short_description')->textarea([ 'value' => $post['short_description'] ]); ?>
            <!-- Description -->
            <?=  froala\froalaeditor\FroalaEditorWidget::widget([
                'model' => $modelTransl,
                'attribute' => 'description',
                'options' => [ // html attributes
                    'id'=>'content',
                    'value'=> $post['description']
                ],
                'clientOptions' => [
                    'toolbarInline' => false,
                    'theme' => 'royal', //optional: dark, red, gray, royal
                    'language' => 'en_gb' // optional: ar, bs, cs, da, de, en_ca, en_gb, en_us ...
                ]
            ]); ?>
            <!-- Source -->
            <?= $form->field($modelTransl, 'source')->textInput([ 'value' => $post['source'] ]) ?>
            <!-- Edit old one or create new translation -->
            <p>
                <?= Html::checkbox("edit_checkbox", false, ['0' => 'Edit', '1' => 'Translation']) ?>
                <span>Check if this is new translation to already existing post, If not this will edit post.</span>
            </p>
            <!-- Submit button -->
            <div class="form-group">
                <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'edit-button']) ?>
            </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

views/site/entry-confirm.php
<?php
use yii\helpers\Html;
?>
<p>You have entered the following information:</p>

<ul>
    <li><label>Name</label>: <?= Html::encode($model->name) ?></li>
    <li><label>Email</label>: <?= Html::encode($model->email) ?></li>
</ul>

views/site/entry.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'email') ?>

    <div class="form-group">
        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
    </div>

<?php ActiveForm::end(); ?>

views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/** @var yii\web\View $this */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron text-center bg-transparent">
        <h1 class="display-4">Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-outline-secondary" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-outline-secondary" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-outline-secondary" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

views/site/login.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap4\ActiveForm $form */
/** @var app\models\LoginForm $model */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>
    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n{input}\n{error}",
            'labelOptions' => ['class' => 'col-lg-1 col-form-label mr-lg-3'],
            'inputOptions' => ['class' => 'col-lg-3 form-control'],
            'errorOptions' => ['class' => 'col-lg-7 invalid-feedback'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"offset-lg-1 col-lg-3 custom-control custom-checkbox\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="offset-lg-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="offset-lg-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        <!--To modify the username/password, please check out the code <code>app\models\User::$users</code>.-->
    </div>
</div>

views/site/say.php
<?php
use yii\helpers\Html;
?>
<?= Html::encode($message) ?>